commit

diff --git a/.github/workflows/pipeline-main.yml b/.github/workflows/pipeline-main.yml
--- a/.github/workflows/pipeline-main.yml
+++ b/.github/workflows/pipeline-main.yml
@@ -19,7 +19,7 @@ jobs:
       - name: Step 2
         run: |
           echo "Running Job 2"
-          exit 1  # Simulate failure
+          exit 1  # Simulating failure
 
   job3:
     needs: job1
@@ -28,7 +28,7 @@ jobs:
       - name: Step 3
         run: |
           echo "Running Job 3"
-          exit 1  # Simulate failure
+          exit 1  # Simulating failure
 
   fail_job:
     needs: [job2, job3]
